---
apiVersion: v1
kind: Namespace
metadata:
   name: hall
   labels:
     name: hall

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hall
  namespace: hall
data:
  cfg.ini: |
    [ApiConfig]
    Address=kubegames-api.default:8433

---
apiVersion: v1
kind: Service
metadata:
  namespace: hall
  name: hall
  annotations:
    proxy: eyJQcm94eVBhdHRlcm4iOiJTZXJ2aWNlIiwiSXRlbXMiOlt7Ik1ldGhvZCI6IkFueSIsIkFnZW50VXJsIjoiL2hhbGwiLCJQcm94eVVybCI6Ii9oYWxsIiwiUG9ydCI6ODQzM31dfQ==
spec:
  type: ClusterIP
  selector:
    app: hall
  ports:
  - protocol: TCP
    port: 8433
    targetPort: 8433

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hall
  name: hall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hall
  template:
    metadata:
      labels:
        app: hall
    spec:
      containers:
      - name: hall
        image: kubegames/hall:latest
        imagePullPolicy: IfNotPresent
        command:
        - "bin/sh"
        - "-c"
        - "./hall -p=8433"
        volumeMounts:
        - mountPath: /config
          name: hall
        ports:
        - containerPort: 8433
      volumes:
        - configMap:
            name: hall
          name: hall

---
apiVersion: v1
kind: Service
metadata:
  namespace: hall
  name: game-web
  annotations:
    proxy: eyJQcm94eVBhdHRlcm4iOiJTZXJ2aWNlIiwiSXRlbXMiOlt7Ik1ldGhvZCI6IkFueSIsIkFnZW50VXJsIjoiL3dlYiIsIlByb3h5VXJsIjoiIiwiUG9ydCI6ODB9XX0=
spec:
  type: ClusterIP
  selector:
    app: game-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hall
  name: game-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-web
  template:
    metadata:
      labels:
        app: game-web
    spec:
      containers:
      - name: game-web
        image: kubegames/web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80